const Actions = {
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_PRODUCTS_PER_PAGE: 'SET_PRODUCTS_PER_PAGE',
  SET_SORTING_OPTION: 'SET_SORTING_OPTION',
  SET_PRICE_RANGE: 'SET_PRICE_RANGE',
  SET_CHOSEN_VIEW: 'SET_CHOSEN_VIEW',
  SET_JWT_TOKEN: 'SET_JWT_TOKEN',
  SET_CATEGORIES_LIST: 'SET_CATEGORIES_LIST',
  TOGGLE_MENU_OPEN: 'TOGGLE_MENU_OPEN',
  SET_CHOSEN_SIZE: 'SET_CHOSEN_SIZE',
  SET_CHOSEN_COLOR: 'SET_CHOSEN_COLOR',
  SET_CHOSEN_QUANTITY: 'SET_CHOSEN_QUANTITY',
  SET_RECENTLY_VIEWED: 'SET_RECENT_VIEWED',
  TOGGLE_SEARCH_BAR_OPEN: 'TOGGLE_SEARCH_BAR_OPEN',
  CHANGE_WISH_LIST: 'CHANGE_WISH_LIST',
  SET_DELIVERY_OPTIONS: 'SET_DELIVERY_OPTIONS',
  CHANGE_SHOPPING_CART: 'CHANGE_SHOPPING_CART',
  SET_USER: 'SET_USER',
  SET_CATEGORY_ID: 'SET_CATEGORY_ID',
  IS_LOGIN_MODAL_OPEN: 'IS_LOGIN_MODAL_OPEN',
  IS_PERSONAL_DETAILS_MODAL_OPEN: 'IS_PERSONAL_DETAILS_MODAL_OPEN',
  SET_GUEST_DATA: 'SET_GUEST_DATA',
  TOGGLE_MODAL_SIZE: 'TOGGLE_MODAL_SIZE'
};

export default Actions;