const Actions = {
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_PRODUCTS_PER_PAGE: 'SET_PRODUCTS_PER_PAGE',
  SET_SORTING_OPTION: 'SET_SORTING_OPTION',
  SET_PRICE_RANGE: 'SET_PRICE_RANGE',
  SET_CHOSEN_VIEW: 'SET_CHOSEN_VIEW',
  SET_JWT_TOKEN: 'SET_JWT_TOKEN',
  SET_CATEGORIES_LIST: 'SET_CATEGORIES_LIST',
  TOGGLE_MENU_OPEN: 'TOGGLE_MENU_OPEN',
  SET_CHOSEN_SIZE: 'SET_CHOSEN_SIZE',
  SET_CHOSEN_QUANTITY: 'SET_CHOSEN_QUANTITY',
  SET_RECENTLY_VIEWED: 'SET_RECENT_VIEWED',
  TOGGLE_SEARCH_BAR_OPEN: 'TOGGLE_SEARCH_BAR_OPEN'
  CHANGE_WISH_LIST: 'CHANGE_WISH_LIST'
};

export default Actions;